dependencies:
- name: demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 4.2.1
- name: quickstart-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: s1p-concerts-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.82
- name: s1p-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.66
- name: s1p-tickets-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.31
